TeamFight:
  Settings:
    maxPerTeam: 2
    objective: 10
    heightLimit: 80
    voidLimit: 10
  Locations:
    worldName: TeamFight
    spawn: 0.0:0.0:0.0:0.0:0.0
    center: 0.0:0.0:0.0:0.0:0.0
    redSpawn: 0.0:0.0:0.0:0.0:0.0
    blueSpawn: 0.0:0.0:0.0:0.0:0.0